import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import "maplibre-gl/dist/maplibre-gl.css";
import { ModelContextProvider } from '@/contexts/model-context';
import { LanguageContextProvider } from '@/contexts/language-context';
import { LocationContextProvider } from '@/contexts/location-context';

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Streets 📍 @ekezia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} ${plusJakartaSans.className}`}>
        <ModelContextProvider>
          <LanguageContextProvider>
            <LocationContextProvider>
              {children}
            </LocationContextProvider>
          </LanguageContextProvider>
        </ModelContextProvider>
      </body>
    </html>
  );
}
