import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ModelContextProvider } from '@/contexts/model-context';
import { LanguageContextProvider } from '@/contexts/language-context';
import { LocationContextProvider } from '@/contexts/location-context';

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Streets 📍 @ekezia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ModelContextProvider>
          <LanguageContextProvider>
            <LocationContextProvider>
              {children}
            </LocationContextProvider>
          </LanguageContextProvider>
        </ModelContextProvider>
      </body>
    </html>
  );
}
