import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModelContextProvider } from '@/contexts/model-context';
import { LanguageContextProvider } from '@/contexts/language-context';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Streets 📍 @ekezia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModelContextProvider>
          <LanguageContextProvider>
            {children}
          </LanguageContextProvider>
        </ModelContextProvider>
      </body>
    </html>
  );
}
